export const MUNICIPALITIES = [
  { id: 'la_trinidad', label: 'La Trinidad' },
  { id: 'baguio', label: 'Baguio City' },
  { id: 'tublay', label: 'Tublay' },
  { id: 'sablan', label: 'Sablan' },
  { id: 'tuba', label: 'Tuba' },
  { id: 'itogon', label: 'Itogon' },
  { id: 'bokod', label: 'Bokod' },
  { id: 'kabayan', label: 'Kabayan' },
  { id: 'buguias', label: 'Buguias' },
  { id: 'mankayan', label: 'Mankayan' },
  { id: 'bakun', label: 'Bakun' },
  { id: 'kibungan', label: 'Kibungan' },
  { id: 'atok', label: 'Atok' },
  { id: 'kapangan', label: 'Kapangan' },
];

export const BARANGAYS = {
  la_trinidad: [
    { id: 'alapang', label: 'Alapang' },
    { id: 'ambiong', label: 'Ambiong' },
    { id: 'bahong', label: 'Bahong' },
    { id: 'balili', label: 'Balili' },
    { id: 'beckel', label: 'Beckel' },
    { id: 'betag', label: 'Betag' },
    { id: 'bineng', label: 'Bineng' },
    { id: 'cruz', label: 'Cruz' },
    { id: 'lubas', label: 'Lubas' },
    { id: 'pico', label: 'Pico' },
    { id: 'poblacion', label: 'Poblacion' },
    { id: 'puguis', label: 'Puguis' },
    { id: 'shilan', label: 'Shilan' },
    { id: 'tawang', label: 'Tawang' },
    { id: 'wangal', label: 'Wangal' },
  ],
  baguio: [
    { id: 'abanao_quirino', label: 'Abanao-Quirino-Zandueta' },
    { id: 'asin_road', label: 'Asin Road' },
    { id: 'aurora_hill', label: 'Aurora Hill' },
    { id: 'bakakeng', label: 'Bakakeng' },
    { id: 'brookspoint', label: 'Brookspoint' },
    { id: 'burnham_legarda', label: 'Burnham-Legarda' },
    { id: 'cabinet_hill', label: 'Cabinet Hill-Teacher Camp' },
    { id: 'camp_7', label: 'Camp 7' },
    { id: 'camp_8', label: 'Camp 8' },
    { id: 'campo_filipino', label: 'Campo Filipino' },
    { id: 'city_camp', label: 'City Camp' },
    { id: 'country_club', label: 'Country Club Village' },
    { id: 'crystal_cave', label: 'Crystal Cave' },
    { id: 'dontogan', label: 'Dontogan' },
    { id: 'fairview', label: 'Fairview Village' },
    { id: 'gibraltar', label: 'Gibraltar' },
    { id: 'greenwater', label: 'Greenwater Village' },
    { id: 'guisad', label: 'Guisad' },
    { id: 'happy_hollow', label: 'Happy Hollow' },
    { id: 'irisan', label: 'Irisan' },
    { id: 'kayang', label: 'Kayang-Hilltop' },
    { id: 'kias', label: 'Kias' },
    { id: 'loakan', label: 'Loakan' },
    { id: 'lower_rock_quarry', label: 'Lower Rock Quarry' },
    { id: 'lualhati', label: 'Lualhati' },
    { id: 'mines_view', label: 'Mines View' },
    { id: 'modern_site', label: 'Modern Site' },
    { id: 'pacdal', label: 'Pacdal' },
    { id: 'pinsao', label: 'Pinsao' },
    { id: 'salud_mitra', label: 'Salud Mitra' },
    { id: 'san_luis', label: 'San Luis Village' },
    { id: 'santo_rosario', label: 'Santo Rosario' },
    { id: 'santo_tomas', label: 'Santo Tomas' },
    { id: 'session_road', label: 'Session Road' },
    { id: 'slaughter_house', label: 'Slaughter House' },
    { id: 'trancoville', label: 'Trancoville' },
    { id: 'upper_rock_quarry', label: 'Upper Rock Quarry' },
  ],
  tublay: [
    { id: 'ambassador', label: 'Ambassador' },
    { id: 'ambongdolan', label: 'Ambongdolan' },
    { id: 'ba_ayan', label: 'Ba-ayan' },
    { id: 'basil', label: 'Basil' },
    { id: 'caponga', label: 'Caponga (Poblacion)' },
    { id: 'daclan', label: 'Daclan' },
    { id: 'tuel', label: 'Tuel' },
    { id: 'tublay_central', label: 'Tublay Central' },
  ],
  sablan: [
    { id: 'bagong', label: 'Bagong' },
    { id: 'balluay', label: 'Balluay' },
    { id: 'banagan', label: 'Banagan' },
    { id: 'baneng', label: 'Baneng' },
    { id: 'boyacaoan', label: 'Boyacaoan' },
    { id: 'bulalacao', label: 'Bulalacao' },
    { id: 'cabadisan', label: 'Cabadisan' },
    { id: 'kamog', label: 'Kamog' },
    { id: 'patar', label: 'Patar' },
    { id: 'poblacion', label: 'Poblacion' },
  ],
  tuba: [
    { id: 'ansagan', label: 'Ansagan' },
    { id: 'camp_1', label: 'Camp 1' },
    { id: 'camp_3', label: 'Camp 3' },
    { id: 'camp_4', label: 'Camp 4' },
    { id: 'nangalisan', label: 'Nangalisan' },
    { id: 'poblacion', label: 'Poblacion' },
    { id: 'san_pascual', label: 'San Pascual' },
    { id: 'tabaan_norte', label: 'Tabaan Norte' },
    { id: 'tabaan_sur', label: 'Tabaan Sur' },
    { id: 'tadiangan', label: 'Tadiangan' },
    { id: 'taloy_norte', label: 'Taloy Norte' },
    { id: 'taloy_sur', label: 'Taloy Sur' },
    { id: 'twin_peaks', label: 'Twin Peaks' },
  ],
  itogon: [
    { id: 'ampucao', label: 'Ampucao' },
    { id: 'dalupirip', label: 'Dalupirip' },
    { id: 'gumatdang', label: 'Gumatdang' },
    { id: 'loacan', label: 'Loacan' },
    { id: 'poblacion', label: 'Poblacion (Itogon Central)' },
    { id: 'tinongdan', label: 'Tinongdan' },
    { id: 'tuding', label: 'Tuding' },
    { id: 'ucab', label: 'Ucab' },
    { id: 'virac', label: 'Virac' },
  ],
  bokod: [
    { id: 'ambuclao', label: 'Ambuclao' },
    { id: 'bila', label: 'Bila' },
    { id: 'bobok_bisal', label: 'Bobok-Bisal' },
    { id: 'daclan', label: 'Daclan' },
    { id: 'ekip', label: 'Ekip' },
    { id: 'karao', label: 'Karao' },
    { id: 'nawal', label: 'Nawal' },
    { id: 'pito', label: 'Pito' },
    { id: 'poblacion', label: 'Poblacion' },
    { id: 'tikey', label: 'Tikey' },
  ],
  kabayan: [
    { id: 'adaoay', label: 'Adaoay' },
    { id: 'anchokey', label: 'Anchokey' },
    { id: 'ballay', label: 'Ballay' },
    { id: 'bashoy', label: 'Bashoy' },
    { id: 'batan', label: 'Batan' },
    { id: 'duacan', label: 'Duacan' },
    { id: 'eddet', label: 'Eddet' },
    { id: 'gusaran', label: 'Gusaran' },
    { id: 'kabayan_barrio', label: 'Kabayan Barrio' },
    { id: 'lusod', label: 'Lusod' },
    { id: 'pacso', label: 'Pacso' },
    { id: 'poblacion', label: 'Poblacion' },
    { id: 'tawangan', label: 'Tawangan' },
  ],
  buguias: [
    { id: 'abatan', label: 'Abatan' },
    { id: 'amgaleyguey', label: 'Amgaleyguey' },
    { id: 'amlimay', label: 'Amlimay' },
    { id: 'baculongan_norte', label: 'Baculongan Norte' },
    { id: 'baculongan_sur', label: 'Baculongan Sur' },
    { id: 'bangao', label: 'Bangao' },
    { id: 'buyacaoan', label: 'Buyacaoan' },
    { id: 'calamagan', label: 'Calamagan' },
    { id: 'catlubong', label: 'Catlubong' },
    { id: 'lengaoan', label: 'Lengaoan' },
    { id: 'loo', label: 'Loo' },
    { id: 'natubleng', label: 'Natubleng' },
    { id: 'poblacion', label: 'Poblacion' },
    { id: 'sebang', label: 'Sebang' },
  ],
  mankayan: [
    { id: 'balili', label: 'Balili' },
    { id: 'bedbed', label: 'Bedbed' },
    { id: 'bulalacao', label: 'Bulalacao' },
    { id: 'cabiten', label: 'Cabiten' },
    { id: 'colalo', label: 'Colalo' },
    { id: 'guinaoang', label: 'Guinaoang' },
    { id: 'paco', label: 'Paco' },
    { id: 'palasaan', label: 'Palasaan' },
    { id: 'poblacion', label: 'Poblacion' },
    { id: 'sapid', label: 'Sapid' },
    { id: 'tabio', label: 'Tabio' },
    { id: 'taneg', label: 'Taneg' },
  ],
  bakun: [
    { id: 'ampusongan', label: 'Ampusongan' },
    { id: 'bagu', label: 'Bagu' },
    { id: 'dalipey', label: 'Dalipey' },
    { id: 'gambang', label: 'Gambang' },
    { id: 'kayapa', label: 'Kayapa' },
    { id: 'poblacion', label: 'Poblacion (Bakun Central)' },
    { id: 'sinacbat', label: 'Sinacbat' },
  ],
  kibungan: [
    { id: 'badeo', label: 'Badeo' },
    { id: 'lubo', label: 'Lubo' },
    { id: 'madaymen', label: 'Madaymen' },
    { id: 'palina', label: 'Palina' },
    { id: 'poblacion', label: 'Poblacion' },
    { id: 'sagpat', label: 'Sagpat' },
    { id: 'tacadang', label: 'Tacadang' },
  ],
  atok: [
    { id: 'abiang', label: 'Abiang' },
    { id: 'caliking', label: 'Caliking' },
    { id: 'cattubo', label: 'Cattubo' },
    { id: 'naguey', label: 'Naguey' },
    { id: 'paoay', label: 'Paoay' },
    { id: 'pasdong', label: 'Pasdong' },
    { id: 'poblacion', label: 'Poblacion' },
    { id: 'sayangan', label: 'Sayangan' },
    { id: 'topdac', label: 'Topdac' },
  ],
  kapangan: [
    { id: 'balakbak', label: 'Balakbak' },
    { id: 'beleng_caoayan', label: 'Beleng-Caoayan' },
    { id: 'boklaoan', label: 'Boklaoan' },
    { id: 'cayapes', label: 'Cayapes' },
    { id: 'cuba', label: 'Cuba' },
    { id: 'datakan', label: 'Datakan' },
    { id: 'gadang', label: 'Gadang' },
    { id: 'gasweling', label: 'Gasweling' },
    { id: 'labueg', label: 'Labueg' },
    { id: 'paykek', label: 'Paykek' },
    { id: 'poblacion', label: 'Poblacion (Kapangan Central)' },
    { id: 'pongayan', label: 'Pongayan' },
    { id: 'pudong', label: 'Pudong' },
    { id: 'sagubo', label: 'Sagubo' },
    { id: 'taba_ao', label: 'Taba-ao' },
  ],
};
